# Generated by Django 4.2.5 on 2023-09-17 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_room_host_message_room_topic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='Subject',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='topic',
            new_name='subject',
        ),
    ]
